### PR TITLE
Added support for "New Wave on Loop"

### PR DESCRIPTION
**Pull request by darthdurden**
If we want a new wave on each loop, we don't want to loop the sound
effect instance, we want to get the next wav after the current one has
ended.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Wow, that actually _was_ pretty simple. Thanks for adding this in!

**Comment by darthdurden** [comment]
Yea I was pretty shocked.  Those changes were my first pass just to kind of see where things stood, and it just worked.

**Comment by flibitijibibo** [comment]
I dunno how hard this is to check, but for the case of loopcount being 255, should this line account for loops that should never end?

https://github.com/BlueLineGames/FNA/blob/c986cef44aa6faa88a7419a53a133603c4f26d18/src/Audio/CueData.cs#L766

I think after 255 loops your loops will go silent...

**Comment by darthdurden** [comment]
Yea I think that should be changed.  I'm not in front of a computer with
XACT on it, but I think the max number is 254... 255 signifying
"indefinite".  I'll verify that later though.

**Comment by darthdurden** [comment]
So if you check the "infinite" checkbox, it changes your loop number to 254
in the GUI.  When it reads in through FNA 255 is what comes in though.  I
think that line should change to:

if (INTERNAL_loopCount != 255 && currentLoop > INTERNAL_loopCount)

Does that make sense to you?

**Comment by flibitijibibo** [comment]
Yeah, 255 _should_ be reserved for infinite loops. Sometimes I forget if I compensate for certain XACT behaviors in other files though, so I've double-compensated more than once before. :P 

This commit should fix infinite loops:

https://github.com/flibitijibibo/FNA/commit/4c572d420e10916f1974eafbe8e3f70e3d22fe6e

**Comment by darthdurden** [comment]
Sweet! Thanks!

**Comment by darthdurden** [comment]
Do you know much about the XACT-based compression?  I see that WMA isn't
supported, which makes sense.  I tried turning on ADPCM (which looks like
it is suppose to be supported) and it barfs on me.  I get a divide by zero
error in OpenALDevice.GenBuffer:

TimeSpan resultDur = TimeSpan.FromSeconds(
bufLen /
(bits / 8) /
channels /
((double) sampleRate)
);

**Comment by flibitijibibo** [comment]
The information found there is gathered from here:

https://github.com/flibitijibibo/FNA/blob/master/src/Audio/WaveBank.cs#L488
https://github.com/flibitijibibo/FNA/blob/master/src/Audio/SoundEffect.cs#L179
https://github.com/flibitijibibo/FNA/blob/master/src/Audio/OpenALDevice.cs#L214

**Pull request merged**
