### PR TITLE
Switch SDL2_KeyboardUtil back to using keycodes

### PR DESCRIPTION
**Pull request by elisee**
The ``SDL2_KeyboardUtil.ToXNA`` method should use keycodes rather than scancodes. XNA keys are layout-dependent, so using an AZERTY keyboard, when I press the A key (which is at the same geographical location as the Q key on a QWERTY keyboard), the key reported by XNA is ``Keys.A``, not ``Keys.Q``. FNA on the other hand, currently erroneously reports ``Keys.Q``

I went spelunking into the history and found that you transitioned from keycodes to scancodes a while back but I found no motivation for that change in the commit log (obviously you also rewrote the whole thing to use a map rather than a big fat switch): https://github.com/flibitijibibo/FNA/commit/5dbe6fc854fc8d2420ef327196ea8370942b3d3a

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Back when I was working on FEZ a few guys in my QA team had trouble with some of the keys the game needed, and for some reason scancodes fixed the issue. I never checked to see if this was fixed by 2.0.0, so it just stuck as a result.

Making this change is a bit scary for compatibility reasons, but I wonder if it'd help to make a USE_SCANCODES define in SDL2_GamePlatform, then have a pair of ToXNA dictionaries for both scancodes and keycodes. It'd make for good compatibility without chucking out alternative keyboard layouts (having the default keys 'just work' has been nice to have, though when it comes time to do input other than TextInputEXT I can see how it'd get ugly).

**Comment by elisee** [comment]
Alright, I'll try and add another commit to the pull request with an optional #define later!

**Comment by flibitijibibo** [comment]
I just pushed a commit for USE_SCANCODES. By default we now use keycodes, but scancodes are still available if needed:

https://github.com/flibitijibibo/FNA/commit/e80eec05ab41cbe60adeefe769b8afac0a6453ae

Let me know if this doesn't work.

**Comment by elisee** [comment]
Works fine, glad to see you made the riskier but more-truthful-to-XNA behavior the default too!

**Pull request closed without merging**
