### PR TITLE
Intel Driver Fix

### PR DESCRIPTION
**Pull request by darthdurden**
Fixed an issue in the faux backbuffer that was giving intel drivers
problems.  We now detach the framebuffer attachments before modifying
them which fixes the issue.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
I'll check out the diffs once they've been fixed, good to know that it was just the attachments causing the issue though.

**Comment by darthdurden** [comment]
Ugh yea... sorry some bad formatting changes going on there.  I didn't notice that. I'll clean it up.

**Comment by darthdurden** [comment]
@flibitijibibo There you go.  Much cleaner.

**Comment by flibitijibibo** [comment]
Merged, with a commit on top:

https://github.com/flibitijibibo/FNA/commit/76b8743e28418aeacd30e298302616bc5fdc9167

**Comment by flibitijibibo** [comment]
And one more...

https://github.com/flibitijibibo/FNA/commit/5c1ff82e277017226f86c937bbaf928e0ece0801

**Pull request merged**
